---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MicroMeta: Meta-analysis version of QCAT

<!-- badges: start -->
<!-- badges: end -->

I provide a meta-analysis framework for Microbiome data sets from different studies based on the summary statistics generated by Quasi-Conditional Association (QCAT) tests. The meta-analysis methods in this package include fixed effect tests, for example, the FE-SKAT test and multivariate test, and random effect tests, like, Het-SKAT and RE-SKAT test. If the taxonomic hierarchy is provided, the tests will be performed on the taxonomic tree to localize the covariate-associated lineages. 

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("DriWater/MicroMeta")
```

## To do list:
I plan to finish the code for the zero-part model (QCAT-GEE), make vignette, and move the code relevant to permutation methods like Score.test.stat.perm, Score.test.stat.zero.perm to CPP, complete the roxygen skeleton in the remainder of this semester. 

