// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// score_test_stat_meta_resampling_c
Rcpp::List score_test_stat_meta_resampling_c(const Rcpp::List& X_perm_list, const Rcpp::List& col_index_list, const Rcpp::List& S_beta_list_meta, const Rcpp::List& I_beta_list_meta, const arma::vec& X_par_index, int n_par_interest_beta);
RcppExport SEXP _MicroMeta_score_test_stat_meta_resampling_c(SEXP X_perm_listSEXP, SEXP col_index_listSEXP, SEXP S_beta_list_metaSEXP, SEXP I_beta_list_metaSEXP, SEXP X_par_indexSEXP, SEXP n_par_interest_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type X_perm_list(X_perm_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type col_index_list(col_index_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type S_beta_list_meta(S_beta_list_metaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type I_beta_list_meta(I_beta_list_metaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type X_par_index(X_par_indexSEXP);
    Rcpp::traits::input_parameter< int >::type n_par_interest_beta(n_par_interest_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_stat_meta_resampling_c(X_perm_list, col_index_list, S_beta_list_meta, I_beta_list_meta, X_par_index, n_par_interest_beta));
    return rcpp_result_gen;
END_RCPP
}
// score_test_stat_zero_meta_resampling_c
Rcpp::List score_test_stat_zero_meta_resampling_c(const Rcpp::List& Z_perm_list, const Rcpp::List& col_zero_index_list, const Rcpp::List& vA_list_meta, const Rcpp::List& Vinv_list_meta, const Rcpp::List& VY_list_meta, const arma::vec& Z_par_index, int n_par_interest_alpha);
RcppExport SEXP _MicroMeta_score_test_stat_zero_meta_resampling_c(SEXP Z_perm_listSEXP, SEXP col_zero_index_listSEXP, SEXP vA_list_metaSEXP, SEXP Vinv_list_metaSEXP, SEXP VY_list_metaSEXP, SEXP Z_par_indexSEXP, SEXP n_par_interest_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Z_perm_list(Z_perm_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type col_zero_index_list(col_zero_index_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type vA_list_meta(vA_list_metaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Vinv_list_meta(Vinv_list_metaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type VY_list_meta(VY_list_metaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z_par_index(Z_par_indexSEXP);
    Rcpp::traits::input_parameter< int >::type n_par_interest_alpha(n_par_interest_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_stat_zero_meta_resampling_c(Z_perm_list, col_zero_index_list, vA_list_meta, Vinv_list_meta, VY_list_meta, Z_par_index, n_par_interest_alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MicroMeta_score_test_stat_meta_resampling_c", (DL_FUNC) &_MicroMeta_score_test_stat_meta_resampling_c, 6},
    {"_MicroMeta_score_test_stat_zero_meta_resampling_c", (DL_FUNC) &_MicroMeta_score_test_stat_zero_meta_resampling_c, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_MicroMeta(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
