# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_test_stat_meta_resampling_c <- function(X_perm_list, col_index_list, S_beta_list_meta, I_beta_list_meta, X_par_index, n_par_interest_beta) {
    .Call(`_MicroMeta_score_test_stat_meta_resampling_c`, X_perm_list, col_index_list, S_beta_list_meta, I_beta_list_meta, X_par_index, n_par_interest_beta)
}

score_test_stat_zero_meta_resampling_c <- function(Z_perm_list, col_zero_index_list, vA_list_meta, Vinv_list_meta, VY_list_meta, Z_par_index, n_par_interest_alpha) {
    .Call(`_MicroMeta_score_test_stat_zero_meta_resampling_c`, Z_perm_list, col_zero_index_list, vA_list_meta, Vinv_list_meta, VY_list_meta, Z_par_index, n_par_interest_alpha)
}

